### PR TITLE
[Proposal] Supporting async validators

### PR DESCRIPTION
**Pull request by ngphi**
- Change generator function into async function to support Koa v2
- Allowing async validators to work just like sync validators

Hi, @buunguyen !
There are some use cases I would like to have an async validator (such as checking an email exist). This PR is a naive implementation which is served as a proposal. I'm looking forward hearing from your feedbacks and suggestions.

### CODE REVIEW

**Comment by buunguyen** [comment]
Test fail. Also, I suppose this requires changing README? The README is probably obsolete anyway, as Koa 2 has been released; not sure if we still need koa-convert. So I'd appreciate a refresh.

**Comment by buunguyen** [comment]
From Travis log, looks like you need to change babelrc to add the right preset/plugin for async/await.

**Comment by buunguyen** [comment]
Thanks. Can you make sure README is up to date with the latest change & Koa? I appreciate the help, thanks.

**Comment by ngphi** [comment]
I have updated README. I'd like to hear from your review. Thanks for your all feedbacks.

**Comment by buunguyen** [comment]
Great, thanks @NPhi!

**Comment by buunguyen** [comment]
I missed this, but you probably need to add `isUserNameNew` to node-validator for the example in README to work. Can you update?

**Pull request merged**
